version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: full_stack_user
      POSTGRES_DB: storefront
      POSTGRES_PASSWORD: password123
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
