version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '2345:5432'
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
